import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { Inter } from "next/font/google";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [file, setFile] = useState();
  const [accessToken, setAccessToken] = useState();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (file) {
      const reader = new FileReader();
      reader.onload = async (e) => {
        const fileJson = JSON.parse(e.target.result);
        try {
          const res = await axios.post("/api/generate", fileJson);
          setAccessToken(res.data.token);
          setFile(null);
        } catch (error) {
          console.error(error);
        }
      };
      reader.readAsText(file);
    }
  };

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
  };

  return (
    <>
      <Head>
        <title>Access Token Generator: We do not save your credentials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <p>Access Token Generator: We do not save your credentials</p>
          </div>
        </div>

        <div
          style={{
            textAlign: "center",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <form onSubmit={handleSubmit}>
            <input type="file" onChange={handleFileChange} />
            <input type="submit" style={{ padding: "1px 16px" }} />
          </form>
          <div
            className={styles.description}
            style={{ marginTop: 16, maxWidth: 750, wordBreak: "break-all" }}
          >
            <p>{accessToken}</p>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/fariswd/fcm-at-generator"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about this generator.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
